### ISSUE TITLE
 No provider for InjectionToken MODULE_MAP! with lazy loading

### ISSUE THREAD

**Issue by dongmei-cao** [swaechter/angularj-universal#19]
This can be reproduced with the latest code (0.0.2) you have here.

You don't need to actually have lazy loading modules in your Angular application. Just run

`$ npm install --save @nguniversal/module-map-ngfactory-loader`

Then add `ModuleMapLoaderModule` in the `app.server.modules` imports array as documented in _https://github.com/angular/angular-cli/wiki/stories-universal-rendering_ or _https://angular.io/guide/universal_.

Now clean build the whole application. When try to access any page, you will see the following error:

Exception in thread "Thread-22" /private/var/folders/rq/5l2f9vzn6ydf3phcsv1mtbk12wpc9s/T/serverbundle3877186372627513417tmp:2931: Error: StaticInjectorError[NgModuleFactoryLoader -> InjectionToken MODULE_MAP]: 
  StaticInjectorError(Platform: core)[NgModuleFactoryLoader -> InjectionToken MODULE_MAP]: 
    NullInjectorError: No provider for InjectionToken MODULE_MAP!
            throw e;
            ^
Error: StaticInjectorError[NgModuleFactoryLoader -> InjectionToken MODULE_MAP]: 
  StaticInjectorError(Platform: core)[NgModuleFactoryLoader -> InjectionToken MODULE_MAP]: 
    NullInjectorError: No provider for InjectionToken MODULE_MAP!
    at _NullInjector.get (/private/var/folders/rq/5l2f9vzn6ydf3phcsv1mtbk12wpc9s/T/serverbundle3877186372627513417tmp:2813:19)
    at resolveToken (/private/var/folders/rq/5l2f9vzn6ydf3phcsv1mtbk12wpc9s/T/serverbundle3877186372627513417tmp:3111:24)
    at tryResolveToken (/private/var/folders/rq/5l2f9vzn6ydf3phcsv1mtbk12wpc9s/T/serverbundle3877186372627513417tmp:3053:16)
    at StaticInjector.get (/private/var/folders/rq/5l2f9vzn6ydf3phcsv1mtbk12wpc9s/T/serverbundle3877186372627513417tmp:2921:20)
    at resolveToken (/private/var/folders/rq/5l2f9vzn6ydf3phcsv1mtbk12wpc9s/T/serverbundle3877186372627513417tmp:3111:24)
    at tryResolveToken (/private/var/folders/rq/5l2f9vzn6ydf3phcsv1mtbk12wpc9s/T/serverbundle3877186372627513417tmp:3053:16)
    at StaticInjector.get (/private/var/folders/rq/5l2f9vzn6ydf3phcsv1mtbk12wpc9s/T/serverbundle3877186372627513417tmp:2921:20)
    at resolveNgModuleDep (/private/var/folders/rq/5l2f9vzn6ydf3phcsv1mtbk12wpc9s/T/serverbundle3877186372627513417tmp:12666:25)
    at _createClass (/private/var/folders/rq/5l2f9vzn6ydf3phcsv1mtbk12wpc9s/T/serverbundle3877186372627513417tmp:12705:68)
    at _createProviderInstance$1 (/private/var/folders/rq/5l2f9vzn6ydf3phcsv1mtbk12wpc9s/T/serverbundle3877186372627513417tmp:12677:26)
com.eclipsesource.v8.V8ScriptExecutionException
	at com.eclipsesource.v8.V8._executeVoidFunction(Native Method)
	at com.eclipsesource.v8.V8.executeVoidFunction(V8.java:1004)
	at com.eclipsesource.v8.V8Object.executeVoidFunction(V8Object.java:418)
	at ch.swaechter.angularjuniversal.v8renderer.V8RenderEngine.startWorking(V8RenderEngine.java:101)
	at ch.swaechter.angularjuniversal.renderer.Renderer.lambda$startRenderer$0(Renderer.java:78)
	at java.lang.Thread.run(Thread.java:748)

**Comment by swaechter** [comment]
Thank you for opening an issue. It looks like the Angular team added the lazy module loading related code to the tutorial and I didn't sync it on my side.

The problem was, that for the module map loader module no LAZY_MODULE_MAP was provided. I rewrote & simplified the files `library/renderadapter.ts` and `library/server.ts` and added the LAZY_MODULE_MAP (You should be able to copy both files). In addition, I updated the README file. For more information see commit e200dd5cc682574dabf20432f0243a990a1fbfa7

**Comment by swaechter** [comment]
In addition, I renamed the webpack.server.config.js to webpack.config.js and updated the NPM build script. 

It's a bit difficult to point to an external tutorial while hoping this tutorial won't change/break stuff ;)

**Comment by dongmei-cao** [comment]
Thanks for fixing it so quickly. Works perfectly now!
